### PR TITLE
Fix BoxCollider Scale Issue

### LINKED ISSUE #6265: Box collider debug helper doesn't update properly
When reshaping a box collider component in the editor, the debug helper does not reflect the new size.

### PR DESCRIPTION
**Pull request by rondoor124**
## Summary

https://github.com/XRFoundation/XREngine/issues/6265

## References

closes #6265

## Checklist
- [ ] CI/CD checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Typescript passing via `npm run check-errors`
  - [ ] Unit & Integration tests passing via `npm run test`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

## Reviewers

@HexaField

### CODE REVIEW

File: packages/engine/src/scene/functions/loaders/BoxColliderFunctions.ts [hunk 1]
```diff
@@ -54,6 +54,19 @@ export const deserializeBoxCollider: ComponentDeserializeFunction = (
   obj3d.traverse((mesh: Mesh) => {
     if (typeof mesh.userData['type'] === 'string') meshObjs.push(mesh)
   })
+
+  obj3d.userData.updateTransform = function () {
```
Comment (HexaField) [inline packages/engine/src/scene/functions/loaders/BoxColliderFunctions.ts:58]: this should be moved to updateBoxCollider, any changes to the object should cause that function to run

**Review by HexaField — CHANGES_REQUESTED** [review]

File: packages/editor/src/commands/ScaleCommand.ts [hunk 2]
```diff
@@ -137,6 +137,7 @@ function updateScale(command: ScaleCommandParams, isUndo: boolean): void {
 
       transformComponent.scale.copy(tempVector)
     }
+    if (obj3d.userData.updateTransform) obj3d.userData.updateTransform()
```
Comment (NPatel10) [inline packages/editor/src/commands/ScaleCommand.ts:140]: This can be moved to `BoxColliderNodeEditor.tsx` and can be invoked by watching the `Selection` state.

File: packages/engine/src/scene/functions/loaders/BoxColliderFunctions.ts (hunk 1 above)
Comment (NPatel10) [reply packages/engine/src/scene/functions/loaders/BoxColliderFunctions.ts:58]: No need to add this function to `updateBoxCollider` but it would be better to create an independent function which accepts `Entity` or `Object3d` and does this operation.

Comment (HexaField) [reply packages/engine/src/scene/functions/loaders/BoxColliderFunctions.ts:58]: yes good idea

File: packages/editor/src/commands/ScaleCommand.ts (hunk 2 above)
Comment (rondoor124) [reply packages/editor/src/commands/ScaleCommand.ts:140]: > 

Hmm.. in the `BoxColliderNodeEditor.tsx`, we could not detect scale transform changes. so I am still going to keep the above code. please let me know the suggestions.

Comment (NPatel10) [reply packages/editor/src/commands/ScaleCommand.ts:140]:
```
const selectionState = useSelectionState()
useEffect(() => {
    if (selectionState.propertyName.value === 'scale') {
      console.log('update the box collider')
    }
  }, [selectionState.propertyName.value])
```

This can be the solution.

File: packages/editor/src/components/properties/BoxColliderNodeEditor.tsx [hunk 3]
```diff
@@ -33,7 +33,7 @@ export const BoxColliderNodeEditor: EditorComponentType = (props) => {
   return (
     <NodeEditor {...props} description={t('editor:properties.boxCollider.description')}>
       <InputGroup name="Trigger" label={t('editor:properties.boxCollider.lbl-isTrigger')}>
-        <BooleanInput value={isTrigger} onChange={updateProperty(null!, 'isTrigger')} />
+        <BooleanInput value={isTrigger} onChange={updateProperty(ColliderComponent, 'isTrigger')} />
```
Comment (HexaField) [inline packages/editor/src/components/properties/BoxColliderNodeEditor.tsx:36]: for now, we don't want to put isTrigger onto the collider component, it will exist as metadata on the physics body already. updateBoxCollider already deals with this.

**Review by HexaField — CHANGES_REQUESTED** [review]

File: packages/editor/src/components/properties/BoxColliderNodeEditor.tsx [hunk 4]
```diff
@@ -22,7 +22,12 @@ export const BoxColliderNodeEditor: EditorComponentType = (props) => {
   const colliderComponent = getComponent(props.node.entity, ColliderComponent)
   const world = useWorld()
   const boxShape = world.physics.getRigidbodyShapes(colliderComponent.body)[0]
-  const isTrigger = isTriggerShape(boxShape)
+  const [isTrigger, setIsTrigger] = useState(isTriggerShape(boxShape))
+
+  const onUpdateTrigger = (value) => {
+    updateTrigger(props.node.entity, value)
```
Comment (HexaField) [inline packages/editor/src/components/properties/BoxColliderNodeEditor.tsx:28]: we dont need to call the new function `updateTrigger` here, we can just call `updateBoxCollider(props.node.entity, { isTrigger: value })`

**Review by HexaField — APPROVED** [review]
