### PR TITLE
Fix vector and euler numeric input and make them reactive

### LINKED ISSUE #7527: [Bug]: Numeric Inputs do not register furthest-right digit of input

### PR DESCRIPTION
**Pull request by AidanCaruso**
## Summary

- Adds a line to Vector3Input and EulerInput to set the value of a hookstate that the input value is later assigned to. This ensures numeric fields always register input.
- Updates components in scale/position/rotate editor control functions so input fields react to changes.
- Euler-input rotations are now only converted from quaternions when updated by editor control functions.

## References

closes #7527 and #7526

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

File: packages/editor/src/components/inputs/EulerInput.tsx [hunk 1]
```diff
@@ -20,20 +23,36 @@ type EulerInputProps = {
   unit?: string
 }
 
+//To be set by editor control functions
+export const EulerState = defineState({
```
Comment (speigg) [inline packages/editor/src/components/inputs/EulerInput.tsx:27]: I wouldn't create a hyperflux state for this very specific functionality. Better to just create a normal `hookstate()` state.

**Review by speigg — CHANGES_REQUESTED** [review]

**Review by speigg — APPROVED** [review]

**Comment by speigg** [comment]
last failing test here seems to be caused by a bug that is fixed in #7615
