### PR TITLE
Misc fixes for profile menu

### LINKED ISSUE #6932: [Bug]: Setting view appears squeezed when user is guest
Here is how it appears when user is a guest:
image

### PR DESCRIPTION
**Pull request by hanzlamateen**
## Summary

- Restored avatar change only allowed in location. As before this commit (https://github.com/XRFoundation/XREngine/commit/db8894c990b9efa0d51ee397ec2f76908538a19d)
- Fixed profile menu issues on home page.

## References

closes #6932

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

File: packages/client-core/src/user/components/UserMenu/menus/ProfileMenu.tsx [hunk 1]
```diff
@@ -384,7 +392,7 @@ const ProfileMenu = ({ className, hideLogin, isPopover, changeActiveMenu, onClos
         <section className={styles.profileBlock}>
           <div className={styles.avatarBlock}>
             <img src={getAvatarURLForUser(userAvatarDetails, userId)} alt="" crossOrigin="anonymous" />
-            {changeActiveMenu && (
+            {allowAvatarChange && changeActiveMenu && (
```
Comment (HexaField) [inline packages/client-core/src/user/components/UserMenu/menus/ProfileMenu.tsx:395]: rather than passing down allowAvatarChange we can enable this only when `getState(EngineState).joinedWorld.value` is true

**Review by HexaField — CHANGES_REQUESTED** [review]

File: packages/client-core/src/user/components/UserMenu/menus/ProfileMenu.tsx (hunk 1 above)
Comment (hanzlamateen) [reply packages/client-core/src/user/components/UserMenu/menus/ProfileMenu.tsx:395]: I passed the flag, so that if at later point we need to allow other pages, i.e. admin panel to allow avatar change. Then all we have to do it to handle `Views.AvatarChange` in `changeActiveMenu` listener and it can allow us to change avatar.

Though if you want I can make it work with `getState(EngineState).sceneLoaded.value` and remove `allowAvatarChange`

Comment (HexaField) [reply packages/client-core/src/user/components/UserMenu/menus/ProfileMenu.tsx:395]: okay, leave as is for now, we can impove it in the future
